// 英語ブランドのみ
export const INITIAL_BRANDS = [
    // ---- デパコス（日本） ----
    "SHISEIDO",
    "KOSÉ",
    "Kanebo",
    "KAO",
    "SK-II", "SK2",
    "SUQQU",
    "DECORTÉ",
    "ALBION",
    "POLA",
    "THREE",
    "RMK",
    "ADDICTION",
    "LUNASOL",
    "IPSA",

    // ---- デパコス（海外） ----
    "CHANEL",
    "DIOR",
    "Yves Saint Laurent",
    "YSL",
    "Giorgio Armani",
    "ARMANI beauty",
    "Lancôme",
    "Estée Lauder",
    "CLINIQUE",
    "Bobbi Brown",
    "M·A·C",
    "NARS",
    "Laura Mercier",
    "Givenchy Beauty",
    "Helena Rubinstein",
    "Guerlain",
    "Kiehl's",
    "Biotherm",
    "shu uemura",

    // ---- プチプラ（日本・グローバル） ----
    "CANMAKE",
    "CEZANNE",
    "MAQuillAGE",
    "INTEGRATE",
    "KATE",
    "Visée",
    "ESPRIQUE",
    "ESPRIQUE Éclat",
    "FASIO",
    "Chifure",
    "Majolica Majorca",
    "Opera",
    "RIMMEL",
    "Ettusais",
    "HADA LABO",
    "Biore",

    "L'Oréal Paris",
    "Maybelline New York",
    "Revlon",
    "NYX Professional Makeup", "NYX",
    "Rimmel London",
    "e.l.f.",
    "Catrice",
    "essence",
    "NIVEA",

    // ---- 韓国ブランド（メイク・スキンケア） ----
    "ETUDE",
    "Etude House",
    "Innisfree",
    "LANEIGE",
    "MISSHA",
    "CLIO",
    "peripera",
    "3CE",
    "STYLENANDA 3CE",
    "rom&nd",
    "HERA",
    "IOPE",
    "AMOREPACIFIC",
    "THE FACE SHOP",
    "Nature Republic",
    "TONYMOLY",
    "Holika Holika",
    "A'PIEU",
    "Banila Co",
    "COSRX",
    "Dr.Jart+",
    "Mediheal",
    "Beauty of Joseon",
    "Abib",
    "AXIS-Y",
    "Pyunkang Yul",
    "Wonjungyo",

    //   日本語表記
    // ---- デパコス（日本） ----
    "資生堂",
    "コーセー",
    "カネボウ",
    "花王",
    "エスケーツー",
    "スック",
    "コスメデコルテ",
    "アルビオン",
    "ポーラ",
    "スリー",
    "アールエムケー",
    "アディクション",
    "ルナソル",
    "イプサ",

    // ---- デパコス（海外） ----
    "シャネル",
    "ディオール",
    "イヴ・サンローラン",
    "イヴサンローラン",
    "ジョルジオ アルマーニ",
    "アルマーニ ビューティ",
    "ランコム",
    "エスティ ローダー",
    "クリニーク",
    "ボビイ ブラウン",
    "マック",
    "ナーズ",
    "ローラ メルシエ",
    "ジバンシイ",
    "ヘレナ ルビンスタイン",
    "ゲラン",
    "キールズ",
    "ビオテルム",
    "シュウ ウエムラ",

    // ---- プチプラ（日本・グローバル） ----
    "キャンメイク",
    "セザンヌ",
    "マキアージュ",
    "インテグレート",
    "ケイト",
    "ヴィセ",
    "エスプリーク",
    "エスプリーク エクラ",
    "ファシオ",
    "ちふれ",
    "マジョリカ マジョルカ",
    "オペラ",
    "リンメル",
    "エテュセ",
    "肌ラボ",
    "ビオレ",

    "ロレアル パリ",
    "メイベリン",
    "レブロン",
    "ニックス",
    "リンメル ロンドン",
    "エルフ",
    "カトリス",
    "エッセンス",
    "ニベア",

    // ---- 韓国ブランド（メイク・スキンケア） ----
    "エチュード",
    "エチュードハウス",
    "イニスフリー",
    "ラネージュ",
    "ミシャ",
    "クリオ",
    "ペリペラ",
    "スリーシーイー",
    "スタイルナンダ 3CE",
    "ロムアンド",
    "ヘラ",
    "アイオペ",
    "アモーレパシフィック",
    "ザ・フェイスショップ",
    "ネイチャーリパブリック",
    "トニーモリー",
    "ホリカホリカ",
    "アピュー",
    "バニラコ",
    "コスアールエックス",
    "ドクタージャルト",
    "メディヒール",
    "ビューティーオブジョセオン",
    "アビブ",
    "アクシスワイ",
    "ピョンカンユル",
    "ウォンジョンヨ",
];



export const LOCAL_STORAGE_BRANDS_KEY = 'MakeLabo_Brands';
